export const initState = {
  client: {},
  cook: {},
  user: {},
  orders: [],
  orderID: {},
  povars: [],
  povarID: {},
  ws: new WebSocket("ws://localhost:3001"),
  ordersNewPovar: [],
  ordersCurrentPovar: [],
  ordersFinishedPovar: [],
  ordersCurrentClient: [],
  ordersFinishedClient: [],
}
